package net.papierkorb2292.command_crafter.editor.processing.string_range_tree

import com.mojang.brigadier.context.StringRange
import com.mojang.serialization.DataResult
import com.mojang.serialization.Dynamic
import com.mojang.serialization.DynamicOps
import net.minecraft.core.RegistryAccess
import net.papierkorb2292.command_crafter.editor.processing.BranchBehaviorProvider
import net.papierkorb2292.command_crafter.editor.processing.codecmod.ExtraDecoderBehavior
import net.papierkorb2292.command_crafter.editor.processing.helper.AnalyzingResult
import net.papierkorb2292.command_crafter.parser.FileMappingInfo
import org.eclipse.lsp4j.Diagnostic
import org.eclipse.lsp4j.DiagnosticSeverity
import org.eclipse.lsp4j.Range
import java.util.*
import kotlin.jvm.optionals.getOrNull

/**
 * A decoder  callback that tracks all errors and the range of the input that caused them.
 *
 * This callback only keeps the errors that are caused by the leaf nodes of a StringRangeTree that is reduced
 * to only the nodes with errors. In other words, errors from a node are ignored if its children already have errors.
 */
class LeafErrorDecoderCallback<TNode : Any>(
    private val root: Dynamic<TNode>,
    override val parentLinks: ParentLinks,
    private val accessedKeysWatcherDynamicOps: AccessedKeysWatcherDynamicOps<TNode>,
    private var branchBehaviorProvider: BranchBehaviorProvider<TNode>,
    override val registries: RegistryAccess?,
    override val onlyContextOps: DynamicOps<TNode>
) : ExtraDecoderBehavior<TNode> {
    private var stack = ArrayList<ErrorStackEntry<TNode>>(16)
    private val lateAdditionMergers = ArrayList<() -> Unit>()
    private val completelyAccessedNodes = Collections.newSetFromMap<TNode>(IdentityHashMap())
    init {
        stack.add(ErrorStackEntry(root.value, 0))
    }

    override fun <TResult> onError(error: DataResult.Error<TResult>, input: TNode) {
        addError(error, input, stack.last().depth)
        popStack()
        branchBehaviorProvider.onDecodeEnd(input)
    }

    override fun markStringParseError(input: TNode) {
        // Don't add error message, diagnostics are already generated by the decoder.
        // Should not be replaced by other decoder errors, because string parsing errors are more specific, so increase depth by 1
        addError(null, input, stack.last().depth + 1)
    }

    private fun addError(error: DataResult.Error<*>?, node: TNode, depth: Int) {
        val stackEntry = stack.last()
        if(!stackEntry.ignoreErrors) {
            stackEntry.comittedDiagnostics.errors += NodeDiagnostics.Entry(error?.message(), node, depth)
            stackEntry.ignoreErrors = true
        }
    }

    override fun <TResult> onResult(result: TResult, isPartial: Boolean, input: TNode) {
        if(isPartial) return
        // Since decoding was successful, all other errors that children added are cleared.
        // Warnings are kept, since they exist even if the result was decoded correctly
        stack.last().clearChildErrors()
        popStack()
        branchBehaviorProvider.onDecodeEnd(input)
    }

    override fun onDecodeStart(input: TNode) {
        pushStack(input)
        branchBehaviorProvider.onDecodeStart(input)
    }

    override fun <TResult> decodeWithBehavior(branchBehaviorModifier: BranchBehaviorProvider.BranchBehaviorModifier, convertToWarnings: Boolean, decodeCallback: () -> TResult): TResult {
        val prevBehavior = this.branchBehaviorProvider
        this.branchBehaviorProvider = branchBehaviorModifier.apply(prevBehavior)
        if(!convertToWarnings) {
            val result = decodeCallback()
            this.branchBehaviorProvider = prevBehavior
            return result
        }
        val prevStack = stack
        val stackTop = prevStack.last()
        stack = ArrayList()
        stack += ErrorStackEntry(stackTop.node, stackTop.depth)
        val prevLateAdditionMergers = ArrayList(lateAdditionMergers)
        lateAdditionMergers.clear()
        val result = decodeCallback()
        val warningEntry = stack.removeLast()
        lateAdditionMergers.forEach { it() }
        warningEntry.comittedDiagnostics.downgradeToWarnings()
        stackTop.comittedDiagnostics.warnings += warningEntry.comittedDiagnostics.warnings
        for((child, childDiagnostics) in warningEntry.childDiagnostics) {
            childDiagnostics.downgradeToWarnings()
            stackTop.offerChild(child, childDiagnostics)
        }
        stack = prevStack
        this.branchBehaviorProvider = prevBehavior
        lateAdditionMergers.clear()
        lateAdditionMergers += prevLateAdditionMergers
        return result
    }

    override fun markErrorLateAddition(): ExtraDecoderBehavior.LateAdditionRunner {
        val stackCopy = ArrayList(stack)
        val branchBehaviorCopy = branchBehaviorProvider.copy()
        stack.last().hasLateAddition = true
        lateAdditionMergers += {
            for(i in stackCopy.lastIndex downTo 1) {
                val entry = stackCopy[i]
                stackCopy[i - 1].offerChild(entry.node, entry.getAllDiagnostics())
            }
        }
        return object : ExtraDecoderBehavior.LateAdditionRunner {
            override fun <T> acceptLateAddition(adder: () -> T): T {
                val prevStack = stack
                val prevBehavior = branchBehaviorProvider
                branchBehaviorProvider = branchBehaviorCopy
                stack = ArrayList(16)
                stack += stackCopy.last()
                val result = adder()
                stack = prevStack
                branchBehaviorProvider = prevBehavior
                return result
            }
        }
    }

    override fun markCompletelyAccessed(input: TNode) {
        completelyAccessedNodes += input
    }

    override val branchBehavior: ExtraDecoderBehavior.BranchBehavior
        get() = branchBehaviorProvider.getBranchBehavior(false)

    private fun pushStack(node: TNode) {
        stack += ErrorStackEntry(node, stack.last().depth + 1)
    }

    private fun popStack() {
        val popped = stack.removeLast()
        val next = stack.last()
        if(popped.hasLateAddition) {
            next.hasLateAddition = true
            return // Will be merged later when generating diagnostics
        }
        next.offerChild(popped.node, popped.getAllDiagnostics())
    }

    fun processUnknownKeys() {
        addMapUnknownKeyDiagnostics(root.value, stack.last().comittedDiagnostics)
    }

    fun generateDiagnostics(ranges: NodeErrorRangeProvider<TNode>, fileMappingInfo: FileMappingInfo, severity: DiagnosticSeverity = DiagnosticSeverity.Error): List<Diagnostic> {
        for(i in lateAdditionMergers.lastIndex downTo 0)
            lateAdditionMergers[i].invoke()
        val nodeDiagnostics = stack.last().getAllDiagnostics()
        return nodeDiagnostics.build(ranges, fileMappingInfo, severity)
    }

    private fun addMapUnknownKeyDiagnostics(map: TNode, nodeDiagnostics: NodeDiagnostics<TNode>) {
        if(map in completelyAccessedNodes)
            return
        val accessed = accessedKeysWatcherDynamicOps.accessedKeys[map]?.toSet() ?: emptySet() // Convert to set so we don't use IdentityHashMap and so it's not modified
        // Use accessedKeysWatcherDynamicOps, so the NodeErrorRangeProvider will work with the keys
        accessedKeysWatcherDynamicOps.getMapEntries(map).result().getOrNull()?.accept { key, child ->
            if(key in accessed) {
                addMapUnknownKeyDiagnostics(child, nodeDiagnostics)
            } else {
                nodeDiagnostics.warnings += NodeDiagnostics.Entry("Unknown key $key", key, 0) // Depth doesn't matter here
            }
        }
        root.ops.getList(map).result().getOrNull()?.accept { child ->
            addMapUnknownKeyDiagnostics(child, nodeDiagnostics)
        }
    }

    inner class PathErrorSuppressingDynamicOps(override val delegate: DynamicOps<TNode>):
        DelegatingDynamicOps<TNode> {
        fun <TResult> onNodeAccess(input: TNode, dataResult: DataResult<TResult>): DataResult<TResult> {
            // Don't show errors for missing keys or invalid list lengths when Minecraft doesn't actually enforce it (like in a path or for a merge)
            if(dataResult.isSuccess && branchBehavior.isAllPossibleEncoded() && input == stack.last().node) {
                stack.last().ignoreErrors = true
            }
            return dataResult
        }

        override fun getMap(input: TNode) = onNodeAccess(input, delegate.getMap(input))
        override fun getMapValues(input: TNode) = onNodeAccess(input, delegate.getMapValues(input))
        override fun getMapEntries(input: TNode) = onNodeAccess(input, delegate.getMapEntries(input))
        override fun getList(input: TNode) = onNodeAccess(input, delegate.getList(input))
        override fun getStream(input: TNode) = onNodeAccess(input, delegate.getStream(input))
        override fun <U> convertTo(outOps: DynamicOps<U>, input: TNode): U {
            if(branchBehavior.isAllPossibleEncoded() && input == stack.last().node) {
                stack.last().ignoreErrors = true
            }
            return delegate.convertTo(outOps, input)
        }
        // Don't suppress errors for getIntStream and such, because those won't be partially matched. TODO: Check specific type of lists
    }

    private class ErrorStackEntry<TNode>(
        val node: TNode,
        // The depth of this entry in the stack. This might not match the position in the list, since some methods temporarily clear the stack.
        val depth: Int,
        val comittedDiagnostics: NodeDiagnostics<TNode> = NodeDiagnostics(),
        val childDiagnostics: MutableMap<TNode, NodeDiagnostics<TNode>> = mutableMapOf(),
        var ignoreErrors: Boolean = false,
        var hasLateAddition: Boolean = false,
    ) {
        fun clearChildErrors() {
            childDiagnostics.values.forEach { it.errors.clear() }
        }

        fun getAllDiagnostics(): NodeDiagnostics<TNode> {
            val diagnostics = NodeDiagnostics(comittedDiagnostics.errors.toMutableList(), comittedDiagnostics.warnings.toMutableList())
            diagnostics.errors += childDiagnostics.values.flatMap { it.errors }
            diagnostics.warnings += childDiagnostics.values.flatMap { it.warnings }
            return diagnostics
        }

        fun offerChild(child: TNode, diagnostics: NodeDiagnostics<TNode>) {
            val prev = childDiagnostics[child]
            if(prev == null) {
                if(diagnostics.errors.isNotEmpty()) {
                    // Errors from this entry should be ignored in favor of errors from the child
                    this.ignoreErrors = true
                    this.comittedDiagnostics.errors.clear()
                }
                childDiagnostics[child] = diagnostics
                return
            }
            // Select option with fewer errors
            if(prev.errors.size != diagnostics.errors.size) {
                if(prev.errors.size > diagnostics.errors.size)
                    childDiagnostics[child] = diagnostics
                return
            }
            // Select option with fewer warnings
            if(prev.warnings.size != diagnostics.warnings.size) {
                if(prev.warnings.size > diagnostics.warnings.size)
                    childDiagnostics[child] = diagnostics
                return
            }

            // Select option with most depth (more specific)
            val prevDiagnosticDepthSum = prev.errors.sumOf { it.depth } + prev.warnings.sumOf { it.depth }
            val newDiagnosticDepthSum = diagnostics.errors.sumOf { it.depth } + diagnostics.warnings.sumOf { it.depth }
            if(prevDiagnosticDepthSum != newDiagnosticDepthSum) {
                if(prevDiagnosticDepthSum < newDiagnosticDepthSum)
                    childDiagnostics[child] = diagnostics
                return
            }

            // Just add diagnostics from both
            prev.errors += diagnostics.errors
            prev.warnings += diagnostics.warnings
        }
    }
    private class NodeDiagnostics<TNode>(
        val errors: MutableList<Entry<TNode>> = mutableListOf(),
        val warnings: MutableList<Entry<TNode>> = mutableListOf()
    ) {
        fun downgradeToWarnings() {
            warnings += errors
            errors.clear()
        }

        fun build(ranges: NodeErrorRangeProvider<TNode>, fileMappingInfo: FileMappingInfo, severity: DiagnosticSeverity): List<Diagnostic> {
            return errors.mapNotNull { entry ->
                entry.createDiagnostic(ranges, fileMappingInfo, severity)
            } + warnings.mapNotNull { entry ->
                entry.createDiagnostic(ranges, fileMappingInfo, DiagnosticSeverity.Warning)
            }
        }

        data class Entry<TNode>(val message: String?, val node: TNode, val depth: Int) {
            fun createDiagnostic(ranges: NodeErrorRangeProvider<TNode>, fileMappingInfo: FileMappingInfo, severity: DiagnosticSeverity): Diagnostic? {
                if(message == null)
                    return null
                val stringRange = ranges.getErrorRange(node) ?: return null
                return Diagnostic().also {
                    it.range = Range(
                        AnalyzingResult.getPositionFromCursor(fileMappingInfo.cursorMapper.mapToSource(stringRange.start + fileMappingInfo.readSkippingChars), fileMappingInfo),
                        AnalyzingResult.getPositionFromCursor(fileMappingInfo.cursorMapper.mapToSource(stringRange.end + fileMappingInfo.readSkippingChars), fileMappingInfo)
                    )
                    it.message = message
                    it.severity = severity
                }
            }
        }
    }

    fun interface NodeErrorRangeProvider<TNode> {
        fun getErrorRange(node: TNode): StringRange?
    }
}