package net.papierkorb2292.command_crafter.editor.processing.string_range_tree

import com.mojang.brigadier.context.StringRange
import com.mojang.serialization.DataResult
import com.mojang.serialization.DynamicOps
import net.minecraft.core.RegistryAccess
import net.papierkorb2292.command_crafter.editor.processing.AccessedKeysWatcherDynamicOps
import net.papierkorb2292.command_crafter.editor.processing.BranchBehaviorProvider
import net.papierkorb2292.command_crafter.editor.processing.DelegatingDynamicOps
import net.papierkorb2292.command_crafter.editor.processing.codecmod.ExtraDecoderBehavior
import net.papierkorb2292.command_crafter.editor.processing.helper.AnalyzingResult
import net.papierkorb2292.command_crafter.parser.FileMappingInfo
import org.eclipse.lsp4j.Diagnostic
import org.eclipse.lsp4j.DiagnosticSeverity
import org.eclipse.lsp4j.Range
import java.util.*

/**
 * A decoder  callback that tracks all errors and the range of the input that caused them.
 *
 * This callback only keeps the errors that are caused by the leaf nodes of a StringRangeTree that is reduced
 * to only the nodes with errors. In other words, errors from a node are ignored if its children already have errors.
 */
class LeafErrorDecoderCallback<TNode : Any>(
    private val stringRangeTree: StringRangeTree<TNode>,
    private val accessedKeysWatcherDynamicOps: AccessedKeysWatcherDynamicOps<TNode>,
    private var branchBehaviorProvider: BranchBehaviorProvider<TNode>,
    override val registries: RegistryAccess?
) : ExtraDecoderBehavior<TNode> {
    private var stack = ArrayList<ErrorStackEntry<TNode>>(16)
    private val lateAdditionMergers = ArrayList<() -> Unit>()
    private val completelyAccessedNodes = Collections.newSetFromMap<TNode>(IdentityHashMap())
    init {
        stack.add(ErrorStackEntry(stringRangeTree.root))
    }
    private fun getNodeRange(node: TNode): StringRange? {
        stringRangeTree.ranges[node]?.let {
            return it
        }
        // Node could be a key, so check if key access happened for it
        val map = accessedKeysWatcherDynamicOps.keyToMap[node] ?: return null
        return stringRangeTree.mapKeyRanges[map]?.firstOrNull { it.first == node }?.second
    }

    override fun <TResult> onError(error: DataResult.Error<TResult>, input: TNode) {
        val range = getNodeRange(input) ?: return
        addError(error, range)
        popStack()
    }

    override fun markStringParseError(input: TNode) {
        val range = getNodeRange(input) ?: return

        // Don't add error message, diagnostics are already generated by the decoder.
        // Should not be replaced by other decoder errors, because string parsing errors are more specific
        addError(null, StringRange.at(range.start))
    }

    private fun addError(error: DataResult.Error<*>?, range: StringRange) {
        val stackEntry = stack.last()
        if(!stackEntry.ignoreErrors) {
            stackEntry.comittedDiagnostics.errors += range to error?.message()
            stackEntry.ignoreErrors = true
        }
    }

    override fun <TResult> onResult(result: TResult, isPartial: Boolean, input: TNode) {
        branchBehaviorProvider.onDecodeEnd(input)
        if(isPartial) return
        // Since decoding was successful, all other errors that children added are cleared.
        // Warnings are kept, since they exist even if the result was decoded correctly
        stack.last().clearChildErrors()
        popStack()
    }

    override fun onDecodeStart(input: TNode) {
        pushStack(input)
        branchBehaviorProvider.onDecodeStart(input)
    }

    override fun <TResult> decodeWithBehavior(branchBehaviorProviderOverride: BranchBehaviorProvider<TNode>?, convertToWarnings: Boolean, decodeCallback: () -> TResult): TResult {
        val prevBehavior = this.branchBehaviorProvider
        this.branchBehaviorProvider = branchBehaviorProviderOverride ?: prevBehavior
        if(!convertToWarnings) {
            val result = decodeCallback()
            this.branchBehaviorProvider = prevBehavior
            return result
        }
        val prevStack = stack
        val stackTop = prevStack.last()
        stack = ArrayList()
        stack += ErrorStackEntry(stackTop.node)
        val prevLateAdditionMergers = ArrayList(lateAdditionMergers)
        lateAdditionMergers.clear()
        val result = decodeCallback()
        val warningEntry = stack.removeLast()
        lateAdditionMergers.forEach { it() }
        warningEntry.comittedDiagnostics.downgradeToWarnings()
        stackTop.comittedDiagnostics.warnings += warningEntry.comittedDiagnostics.warnings
        for((child, childDiagnostics) in warningEntry.childDiagnostics) {
            childDiagnostics.downgradeToWarnings()
            stackTop.offerChild(child, childDiagnostics)
        }
        stack = prevStack
        this.branchBehaviorProvider = prevBehavior
        lateAdditionMergers.clear()
        lateAdditionMergers += prevLateAdditionMergers
        return result
    }

    override fun getParent(child: TNode): TNode? = stringRangeTree.getParent(child, accessedKeysWatcherDynamicOps)

    override fun markErrorLateAddition(): ExtraDecoderBehavior.LateAdditionRunner {
        val stackCopy = ArrayList(stack)
        stack.last().hasLateAddition = true
        lateAdditionMergers += {
            for(i in stackCopy.lastIndex downTo 1) {
                val entry = stackCopy[i]
                stackCopy[i - 1].offerChild(entry.node, entry.getAllDiagnostics())
            }
        }
        return object : ExtraDecoderBehavior.LateAdditionRunner {
            override fun <T> acceptLateAddition(adder: () -> T): T {
                val prevStack = stack
                stack = ArrayList(16)
                stack += stackCopy.last()
                val result = adder()
                stack = prevStack
                return result
            }
        }
    }

    override fun markCompletelyAccessed(input: TNode) {
        completelyAccessedNodes += input
    }

    override val branchBehavior: ExtraDecoderBehavior.BranchBehavior
        get() = branchBehaviorProvider.getBranchBehavior(false)

    override val decodeNonCanonical: Boolean
        get() = branchBehaviorProvider.shouldDecodeNonCanonical()

    private fun pushStack(node: TNode) {
        stack += ErrorStackEntry(node)
    }

    private fun popStack() {
        val popped = stack.removeLast()
        val next = stack.last()
        if(popped.hasLateAddition) {
            next.hasLateAddition = true
            return // Will be merged later when generating diagnostics
        }
        next.offerChild(popped.node, popped.getAllDiagnostics())
    }

    fun generateDiagnostics(fileMappingInfo: FileMappingInfo, severity: DiagnosticSeverity = DiagnosticSeverity.Error): List<Diagnostic> {
        for(i in lateAdditionMergers.lastIndex downTo 0)
            lateAdditionMergers[i].invoke()
        val nodeDiagnostics = stack.last().getAllDiagnostics()
        addMapUnknownKeyDiagnostics(stringRangeTree.root, nodeDiagnostics)
        return nodeDiagnostics.build(fileMappingInfo, severity)
    }

    private fun addMapUnknownKeyDiagnostics(map: TNode, nodeDiagnostics: NodeDiagnostics) {
        if(map in completelyAccessedNodes)
            return
        val mapKeys = stringRangeTree.mapKeyRanges[map] ?: return
        val accessed = accessedKeysWatcherDynamicOps.accessedKeys[map]?.toSet() ?: emptySet() // Convert to set so we don't use IdentityHashMap
        for((key, range) in mapKeys) {
            // Key must exist (snbt grammar might add unknown keys)
            accessedKeysWatcherDynamicOps.getGeneric(map, key).result().ifPresent { child ->
                if(key in accessed) {
                    addMapUnknownKeyDiagnostics(child, nodeDiagnostics)
                } else {
                    nodeDiagnostics.warnings += range to "Unused key $key"
                }
            }
        }
    }

    inner class PathErrorSuppressingDynamicOps(override val delegate: DynamicOps<TNode>):
        DelegatingDynamicOps<TNode> {
        fun <TResult> onNodeAccess(input: TNode, dataResult: DataResult<TResult>): DataResult<TResult> {
            // Don't show errors for missing keys or invalid list lengths when Minecraft doesn't actually enforce it (like in a path or for a merge)
            if(dataResult.isSuccess && branchBehavior == ExtraDecoderBehavior.BranchBehavior.ALL_POSSIBLE_ENCODED && input == stack.last().node) {
                stack.last().ignoreErrors = true
            }
            return dataResult
        }

        override fun getMap(input: TNode) = onNodeAccess(input, delegate.getMap(input))
        override fun getMapValues(input: TNode) = onNodeAccess(input, delegate.getMapValues(input))
        override fun getMapEntries(input: TNode) = onNodeAccess(input, delegate.getMapEntries(input))
        override fun getList(input: TNode) = onNodeAccess(input, delegate.getList(input))
        override fun getStream(input: TNode) = onNodeAccess(input, delegate.getStream(input))
        override fun getByteBuffer(input: TNode) = onNodeAccess(input, delegate.getByteBuffer(input))
        override fun getIntStream(input: TNode) = onNodeAccess(input, delegate.getIntStream(input))
        override fun getLongStream(input: TNode) = onNodeAccess(input, delegate.getLongStream(input))
    }

    private class ErrorStackEntry<TNode>(
        val node: TNode,
        val comittedDiagnostics: NodeDiagnostics = NodeDiagnostics(),
        val childDiagnostics: MutableMap<TNode, NodeDiagnostics> = mutableMapOf(),
        var ignoreErrors: Boolean = false,
        var hasLateAddition: Boolean = false,
    ) {
        fun clearChildErrors() {
            childDiagnostics.values.forEach { it.errors.clear() }
        }

        fun getAllDiagnostics(): NodeDiagnostics {
            val diagnostics = NodeDiagnostics(comittedDiagnostics.errors.toMutableList(), comittedDiagnostics.warnings.toMutableList())
            diagnostics.errors += childDiagnostics.values.flatMap { it.errors }
            diagnostics.warnings += childDiagnostics.values.flatMap { it.warnings }
            return diagnostics
        }

        fun offerChild(child: TNode, diagnostics: NodeDiagnostics) {
            val prev = childDiagnostics[child]
            if(prev == null) {
                if(diagnostics.errors.isNotEmpty()) {
                    // Errors from this entry should be ignored in favor of errors from the child
                    this.ignoreErrors = true
                    this.comittedDiagnostics.errors.clear()
                }
                childDiagnostics[child] = diagnostics
                return
            }
            // Select option with fewer errors
            if(prev.errors.size != diagnostics.errors.size) {
                if(prev.errors.size > diagnostics.errors.size)
                    childDiagnostics[child] = diagnostics
                return
            }
            // Select option with fewer warnings
            if(prev.warnings.size != diagnostics.warnings.size) {
                if(prev.warnings.size > diagnostics.warnings.size)
                    childDiagnostics[child] = diagnostics
                return
            }

            // Select option with smaller (more specific) diagnostics
            val prevDiagnosticTotalLength = prev.errors.sumOf { it.first.length } + prev.warnings.sumOf { it.first.length }
            val newDiagnosticTotalLength = diagnostics.errors.sumOf { it.first.length } + diagnostics.warnings.sumOf { it.first.length }
            if(prevDiagnosticTotalLength != newDiagnosticTotalLength) {
                if(prevDiagnosticTotalLength > newDiagnosticTotalLength)
                    childDiagnostics[child] = diagnostics
                return
            }

            // Just add diagnostics from both
            prev.errors += diagnostics.errors
            prev.warnings += diagnostics.warnings
        }
    }
    private class NodeDiagnostics(
        val errors: MutableList<kotlin.Pair<StringRange, String?>> = mutableListOf(),
        val warnings: MutableList<kotlin.Pair<StringRange, String?>> = mutableListOf()
    ) {
        fun downgradeToWarnings() {
            warnings += errors
            errors.clear()
        }

        fun build(fileMappingInfo: FileMappingInfo, severity: DiagnosticSeverity): List<Diagnostic> {
            fun createDiagnostic(message: String, range: StringRange, severity: DiagnosticSeverity) =
                Diagnostic().also {
                    it.range = Range(
                        AnalyzingResult.getPositionFromCursor(fileMappingInfo.cursorMapper.mapToSource(range.start + fileMappingInfo.readSkippingChars), fileMappingInfo),
                        AnalyzingResult.getPositionFromCursor(fileMappingInfo.cursorMapper.mapToSource(range.end + fileMappingInfo.readSkippingChars), fileMappingInfo)
                    )
                    it.message = message
                    it.severity = severity
                }

            return errors.mapNotNull { (range, message) ->
                if(message == null)
                    return@mapNotNull null
                createDiagnostic(message, range, severity)
            } + warnings.mapNotNull { (range, message) ->
                if(message == null)
                    return@mapNotNull null
                createDiagnostic(message, range, DiagnosticSeverity.Warning)
            }
        }
    }
}